project_id = "anutyhusiqhundjxvztu"

[functions.generate-experiments]
verify_jwt = false

[functions.analyze-decision]
verify_jwt = false

[functions.suggest-criteria]
verify_jwt = false

[functions.generate-criteria-facts]
verify_jwt = false
